# App
app:
  name: upp-service
  secret-code: omazpgscqcbwbict

# Spring DataSource
spring:
  jackson.serialization.FAIL_ON_EMPTY_BEANS: false

  datasource:
    url: jdbc:mysql://localhost:3306/upp?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root

    # If the connection is too long in idle state
    dbcp.test-while-idle: true
    dbcp.validation-query: SELECT 1
    initialization-mode: always

  # JPA-Hibernate
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy

  mail:
    host: smtp.gmail.com
    port: 587
    username: nikolinaapetrovic97@gmail.com
    password: omazpgscqcbwbict
    properties.mail.smtp.starttls.enable: true

# Camunda
camunda:
    bpm.admin-user:
      id: demo
      password: demo
